# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
