on:
  push:

name: 'Bundle simulator'

env:
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  WEB3_INFURA_PROJECT_ID:  ${{ secrets.WEB3_INFURA_PROJECT_ID }} 
  ETH_RPC_URL:  ${{ secrets.ETH_RPC_URL }} 
  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - uses: extractions/setup-just@v1
    - name: Forge Build
      id: build
      run: just build
