on:
  push:
    paths:
      - 'tests/**/*.py'
      - 'contracts/**/*.sol'

name: Brownie tests

env:
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v3

      # - name: Setup Node.js
      #   run: yarn install

      - name: Install Ganache
        run: npm install -g ganache-cli@6.12.2

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Configure test state
        run: brownie networks add development mainnet-fork1 cmd="ganache-cli" host=http://127.0.0.1 fork="$ETH_RPC_URL@14161345" accounts=10 mnemonic=brownie port=8545 timeout=100

      - name: Run Tests
        run: brownie test --network mainnet-fork1
